version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports: 
      - 5432:5432  
    volumes:
      - ./postgres/database:/data/db