version: 2.1

jobs:
  yarn-install:
    docker:
      - image: node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-install-{{ checksum "package.json" }}
            - yarn-install
          paths:
            - node_modules
      - run:
          name: project installation
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  ci:
    docker:
      - image: node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run :
          name: run test and check style
          command: yarn ci

workflows:
  version: 2.1
  build:
    jobs:
      - yarn-install
      - ci:
          requires:
            - yarn-install
  
  
